sudo: required
services:
  - docker
env:
  global:
    - GIT_SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_9bc875be616e_key -iv $encrypted_9bc875be616e_iv -in cloud-k8s-239005-e93ec6b459fb.json.enc -out cloud-k8s-239005-e93ec6b459fb.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components upadte kubectl
  - gcloud auth activate-service-account --key-file cloud-k8s-239005-e93ec6b459fb.json
  - gcloud config set project cloud-k8s-239005
  - gcloud config set compute/zone southamerica-east1-a
  - gcloud container clusters get-credentials cloud-k8s
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t ewfnz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ewfnz/react-test npm test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
