sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_9bc875be616e_key -iv $encrypted_9bc875be616e_iv -in cloud-k8s-239005-e93ec6b459fb.json.enc -out cloud-k8s-239005-e93ec6b459fb.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components upadte kubectl
  - gcloud auth activate-service-account --key-file service-account.json
